name: Benchmark

on:
  workflow_dispatch:

jobs:
  bench-coke:
    name: bench coke
    runs-on: ubuntu-22.04
    steps:
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install -y libgtest-dev valgrind
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: kedixa/coke
        ref: master
    - name: Build
      run: |
        bazel build ...
        echo "### Bench Go" >> bench.md
        ./bazel-bin/benchmark/bench_go -c 32 -n 8 -t 2000000 -y >> bench.md

        echo -e "\n### Bench Timer" >> bench.md
        ./bazel-bin/benchmark/bench_timer -h 12 -p 8 -t 2000000 -y >> bench.md

    - name: Comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs/promises')
          const data = await fs.readFile('./bench.md', 'utf-8')
          await github.rest.issues.createComment({
            issue_number: 4,
            repo: 'test',
            owner: 'kedixa',
            body: data
          })
