name: Benchmark

on:
  workflow_dispatch:

jobs:
  bench-coke:
    name: Coke Benchmark
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: kedixa/coke
        ref: dev
    - name: Build
      run: |
        bazel build //benchmark/...

        (echo "# Benchmark"
        echo "The benchmark runs in Github Actions"
        echo ""

        echo "## Environment"
        echo "\`\`\`"
        lscpu
        lsmem
        echo "\`\`\`"
        echo ""

        echo "## Go"
        ./bazel-bin/benchmark/bench_go -c 32 -n 8 -t 2000000 -y
        echo ""

        echo "## Timer"
        ./bazel-bin/benchmark/bench_timer -h 12 -p 8 -t 2000000 -y
        echo ""
        ) > bench.md

    - name: Comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs/promises')
          const data = await fs.readFile('./bench.md', 'utf-8')
          await github.rest.issues.createComment({
            issue_number: 4,
            repo: 'test',
            owner: 'kedixa',
            body: data
          })
