on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: quay.io/centos/centos:stream8
    steps:
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
    - name: Build With GCC
      run: |
        echo $CC $CXX $BAZEL_OPTS
