on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
        - cc: gcc-10
          cxx: g++-10
          opts: --cxxopt=-fcoroutines

    steps:
    - name: Prepare
      run: |
        sudo apt install -y libgtest-dev valgrind
    - uses: actions/checkout@v3
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
    - name: Build With GCC
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
        BAZEL_OPTS: ${{ matrix.compiler.opts }}
      run: |
        echo $CC $CXX $BAZEL_OPTS
