on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
    - name: step1
      run: |
        echo "hello world"
