on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        compiler:
        - cc: gcc-10
          cxx: g++-10
          opts: --cxxopt=-fcoroutines

    steps:
    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1
    #  with:
    #    limit-access-to-actor: true
    - name: Build With GCC
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
        BAZEL_OPTS: ${{ matrix.compiler.opts }}
      run: |
        echo $CC $CXX $BAZEL_OPTS
        echo "a" > a.txt
    - uses: actions/upload-artifact@v3
      with:
        name: a.txt
        path: a.txt
