on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc-version: ["10", "11"]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      env:
        CC: gcc-${{ matrix.gcc-version }}
        CXX: g++-${{ matrix.gcc-version }}
      run: |
        sudo apt install -y libgtest-dev valgrind
        git clone https://github.com/kedixa/corkflow.git
        cd corkflow && bazel build ... --cxxopt=-fcoroutines && bazel test ... --config=memcheck
