on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc-version: ["10", "11", "12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display
      run: |
        git clone https://github.com/kedixa/corkflow.git
        ls /usr/bin/gcc*
        ls /usr/bin/clang*
