name: Comment on labeled

on:
  issues:
    types: [labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'test'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
