on:
  workflow_dispatch:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  run-script:
    name: run-script-name
    runs-on: ubuntu-22.04
    steps:
      - name: echo github
        run: |
          cat << EEEOOOFFF
          ${{ toJson(github) }}
          EEEOOOFFF
