on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
    - name: Prepare
      run: |
        apt update
        apt install -y software-properties-common
        add-apt-repository ppa:ubuntu-toolchain-r/test
        apt install -y gcc-11 g++-11 libgtest-dev libssl-dev git cmake
    - uses: actions/checkout@v3
      with:
        repository: kedixa/coke
    - uses: actions/checkout@v3
      with:
        repository: sogou/workflow
        ref: v0.10.7
        path: workflow
        fetch-depth: 1
    - name: aaa
      run: ls -lhtra
